<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:dpc="http://esa.ssa/dpc/2.1/CorrelationServiceSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:tns="http://esa.ssa/dpc/2.1/CorrelationService/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ssa="http://esa.ssa.common/ssaRuntimeService/" name="CorrelationService" targetNamespace="http://esa.ssa/dpc/2.1/CorrelationService/">
	<wsdl:import namespace="http://esa.ssa/dpc/2.1/CorrelationServiceSchema" location="./CorrelationServiceSchema.wsdl"/>
	<wsdl:import namespace="http://esa.ssa.common/ssaRuntimeService/" location="../../ssaHeaders/ssaRuntimeService.wsdl" />
	<wsdl:binding name="CorrelationServiceInterfaceBinding" type="dpc:CorrelationServiceInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<!-- ======== OPERATIONS =========  -->
		<wsdl:operation name="correlateObservations">
			<soap:operation soapAction="http://esa.ssa/dpc/2.1/CorrelationService/correlateObservations/"/>
			<wsdl:input>
				<soap:body parts="in" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="out" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal" />
			</wsdl:output>
			<wsdl:fault name="correlateObservationsFault">
				<soap:fault name="correlateObservationsFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="correlateThirdPartyData">
			<soap:operation soapAction="http://esa.ssa/dpc/2.1/CorrelationService/correlateThirdPartyData/"/>
			<wsdl:input>
				<soap:body parts="in" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="out" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal" />
			</wsdl:output>
			<wsdl:fault name="correlateThirdPartyDataFault">
				<soap:fault name="correlateThirdPartyDataFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="CorrelationService">
		<wsdl:port name="CorrelationServiceInterfacePort" binding="tns:CorrelationServiceInterfaceBinding">
			<soap:address location="http://esa.ssa/dpc/2.1/CorrelationService/CorrelationService/CorrelationServiceInterfacePort"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
