<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	xmlns:e3d="http://eiscat.com/SST" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://eiscat.com/SSTService"
	name="SSTService" 
	targetNamespace="http://eiscat.com/SSTService">

	<wsdl:import namespace="http://eiscat.com/SST" location="testSchema.wsdl"/>
	<wsdl:binding name="SSTServiceBinding" type="e3d:SSTServiceInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

		<wsdl:operation name="getObservationData">
			<soap:operation soapAction="http://eiscat.com/SST/getObservationData/" style="document"/>
			<wsdl:input>
				<soap:body parts="in" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="out" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="SSTService">
		<wsdl:port name="SSTServiceInterfacePort" binding="tns:SSTServiceBinding">
			<soap:address location="http://eiscat.com/SSTService/SSTServiceInterfacePort"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
