<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:ndm="urn:ccsds:recommendation:navigation:schema:ndmxml"
	xmlns:e3dt="e3d:types"
	name="e3d" 
	targetNamespace="http://eiscat.com/SST">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ndm="urn:ccsds:recommendation:navigation:schema:ndmxml" elementFormDefault="unqualified" attributeFormDefault="unqualified">
			<xsd:import namespace="urn:ccsds:recommendation:navigation:schema:ndmxml" schemaLocation="./commonSSTDataModel/CCSDS/ndmxml-1.0-namespace-1.1.xsd"/>
			<xsd:import namespace="e3d:types" schemaLocation="./target.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="RequestObservationDataRequestMessageType">
		<wsdl:part name="in" element="ndm:tdmType"/>
	</wsdl:message>
	<wsdl:message name="SubmitObservationDataResponseMessageType">
		<wsdl:part name="out" element="ndm:tdmType"/>
	</wsdl:message>
	<wsdl:portType name="SSTServiceInterface">
		<wsdl:operation name="getObservationData">
			<wsdl:input message="RequestObservationDataRequestMessageType"/>
			<wsdl:output message="SubmitObservationDataResponseMessageType"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>
