<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions 
xmlns:xs="http://www.w3.org/2001/XMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xmlns:plink="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" 
xmlns:wsdlsoap11="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:wsdlsoap12="http://schemas.xmlsoap.org/wsdl/soap12/" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:soap11enc="http://schemas.xmlsoap.org/soap/encoding/" 
xmlns:soap11env="http://schemas.xmlsoap.org/soap/envelope/" 
xmlns:soap12env="http://www.w3.org/2003/05/soap-envelope" 
xmlns:soap12enc="http://www.w3.org/2003/05/soap-encoding" 
xmlns:wsa="http://schemas.xmlsoap.org/ws/2003/03/addressing" 
xmlns:xop="http://www.w3.org/2004/08/xop/include" 
xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" 
xmlns:tns="e3d.test" 
xmlns:ccsds="urn:ccsds:recommendation:navigation:schema:ndmxml"
targetNamespace="e3d.test" 
name="Application">
	<wsdl:types>
		<xs:schema targetNamespace="e3d.test" elementFormDefault="qualified">
		<xsd:import namespace="urn:ccsds:recommendation:navigation:schema:ndmxml" schemaLocation="./commonSSTDataModel/CCSDS/ndmxml-1.0-master.xsd"/>
			<xs:complexType name="target">
				<xs:sequence>
					<xs:element name="oid" type="xs:integer" minOccurs="0" nillable="true"/>
				</xs:sequence>
			</xs:complexType>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="target">
		<wsdl:part name="target" element="tns:target"/>
	</wsdl:message>
	<wsdl:message name="targetResponse">
		<wsdl:part name="targetResponse" element="tns:ccsds:tdm"/>
	</wsdl:message>
	<wsdl:service name="e3dService">
		<wsdl:port name="Application" binding="tns:Application">
			<wsdlsoap11:address location="http://localhost:8000/"/>
		</wsdl:port>
	</wsdl:service>
	<wsdl:portType name="Application">
		<wsdl:operation name="target" parameterOrder="target">
			<wsdl:input name="target" message="tns:target"/>
			<wsdl:output name="targetResponse" message="tns:targetResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="Application" type="tns:Application">
		<wsdlsoap11:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="target">
			<wsdlsoap11:operation soapAction="target" style="document"/>
			<wsdl:input name="target">
				<wsdlsoap11:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="targetResponse">
				<wsdlsoap11:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>
