<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:dpc="http://esa.ssa/dpc/2.1/OrbitDeterminationServiceSchema" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://esa.ssa/dpc/2.1/OrbitDeterminationService" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:ssa="http://esa.ssa.common/ssaRuntimeService/" name="OrbitDeterminationService" targetNamespace="http://esa.ssa/dpc/2.1/OrbitDeterminationService">
	<wsdl:import namespace="http://esa.ssa/dpc/2.1/OrbitDeterminationServiceSchema" location="./OrbitDeterminationServiceSchema.wsdl"/>
	<wsdl:import namespace="http://esa.ssa.common/ssaRuntimeService/" location="../../ssaHeaders/ssaRuntimeService.wsdl" />
	<wsdl:binding name="OrbitDeterminationServiceInterfaceBinding" type="dpc:OrbitDeterminationServiceInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<!-- ======== OPERATIONS =========  -->
		<wsdl:operation name="performInitial">
			<soap:operation soapAction="http://esa.ssa.dpc/1.2/OrbitDeterminationService/performInitial/"/>
			<wsdl:input>
				<soap:body parts="in" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="out" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal" />
			</wsdl:output>
			<wsdl:fault name="performInitialFault">
				<soap:fault name="performInitialFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="performRoutine">
			<soap:operation soapAction="http://esa.ssa.dpc/1.2/OrbitDeterminationService/performRoutine/"/>
			<wsdl:input>
				<soap:body parts="in" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="out" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal" />
			</wsdl:output>
			<wsdl:fault name="performRoutineFault">
				<soap:fault name="performRoutineFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="OrbitDeterminationService">
		<wsdl:port name="OrbitDeterminationServiceInterfacePort" binding="tns:OrbitDeterminationServiceInterfaceBinding">
			<soap:address location="http://esa.ssa/dpc/2.1/OrbitDeterminationService/OrbitDeterminationService/OrbitDeterminationServiceInterfacePort"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
