<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:dpc="http://esa.ssa/dpc/2.1/CatalogueQualityMonitoringServiceSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://esa.ssa/dpc/2.1/CatalogueQualityMonitoringService/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ssa="http://esa.ssa.common/ssaRuntimeService/" name="CatalogueQualityMonitoringService" targetNamespace="http://esa.ssa/dpc/2.1/CatalogueQualityMonitoringService/">
	<wsdl:import namespace="http://esa.ssa/dpc/2.1/CatalogueQualityMonitoringServiceSchema" location="./CatalogueQualityMonitoringServiceSchema.wsdl"/>
	<wsdl:import namespace="http://esa.ssa.common/ssaRuntimeService/" location="../../ssaHeaders/ssaRuntimeService.wsdl"/>
	<wsdl:binding name="CatalogueQualityMonitoringServiceInterfaceBinding" type="dpc:CatalogueQualityMonitoringServiceInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<!-- ======== OPERATIONS =========  -->
		<wsdl:operation name="checkOrbitValidityPeriod">
			<soap:operation soapAction="http://esa.ssa/dpc/2.1/CatalogueQualityMonitoringService/checkOrbitValidityPeriod/"/>
			<wsdl:input>
				<soap:body parts="in" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="out" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="checkOrbitValidityPeriodFault">
				<soap:fault name="checkOrbitValidityPeriodFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="setValidityPeriod">
			<soap:operation soapAction="http://esa.ssa/dpc/2.1/CatalogueQualityMonitoringService/setValidityPeriod/"/>
			<wsdl:input>
				<soap:body parts="in" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="out" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="setValidityPeriodFault">
				<soap:fault name="setValidityPeriodFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="setAccuracyLimits">
			<soap:operation soapAction="http://esa.ssa/dpc/2.1/CatalogueQualityMonitoringService/setAccuracyLimits/"/>
			<wsdl:input>
				<soap:body parts="in" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="out" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="setAccuracyLimitsFault">
				<soap:fault name="setAccuracyLimitsFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="generateObservationRequest">
			<soap:operation soapAction="http://esa.ssa/dpc/2.1/CatalogueQualityMonitoringService/generateObservationRequest/"/>
			<wsdl:input>
				<soap:body parts="in" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body parts="out" use="literal"/>
				<soap:header message="ssa:SSARuntimeMessage" part="header" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="generateObservationRequestFault">
				<soap:fault name="generateObservationRequestFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="CatalogueQualityMonitoringService">
		<wsdl:port name="CatalogueQualityMonitoringServiceInterfacePort" binding="tns:CatalogueQualityMonitoringServiceInterfaceBinding">
			<soap:address location="http://esa.ssa/dpc/2.1/CatalogueQualityMonitoringService/OrbitService/CatalogueQualityMonitoringServiceInterfacePort"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
